version: "1.3.0"
global:
  projectName: "mySuperApp"
  environment: "production"
  defaultImagePullPolicy: "IfNotPresent"
  network:
    name: "my-app-network"
    alias: "appnet"
    driver: "bridge"


appName: "web"  # обов'язково вказується для основного чарту, повинно спывпадати з ім'ям сервісу в docker-compose.yml
rolling-update: true
replicas: 2
image:
  repository: "jmalloc/echo-server"
  tag: "v0.3.7"


database:
  image:
    repository: "postgres"
    tag: "15-alpine"
  volumeSize: "10Gi"
  environment:
    POSTGRES_PASSWORD: "mySuperApp1"
    POSTGRES_USER: "mySuperApp2"
    POSTGRES_DB: "mySuperApp1" 

cache:
  image:
    repository: "valkey/valkey"
    tag: "8-alpine"
  port: 6379 

web2:
  image:
    repository: "jmalloc/echo-server"
    tag: "v0.3.7"
  replicas: 3
  rolling-update: true