title: Docker Compose Wrapper
description: A powerful wrapper for Docker Compose with advanced features
baseurl: "/docker-compose-wrapper/"
url: "https://your-server-support.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 